# Generated by Django 3.1.1 on 2020-10-03 18:37

from django.db import migrations, models
import django.db.models.deletion
import file_manager.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('absolute_file_path', models.CharField(max_length=2048)),
                ('filename', models.CharField(max_length=256)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to=file_manager.models.backup_file_upload)),
                ('upload_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_files', to='file_manager.uploadserver')),
            ],
            options={
                'ordering': ['upload_server', 'filename'],
                'unique_together': {('upload_server', 'absolute_file_path')},
            },
        ),
    ]
